const bookings = [
  { guest: "Maya Patel", route: "Monsoon in Munnar", date: "18 Aug 2026", status: "Confirmed", amount: "₹57,800" },
  { guest: "Noah Williams", route: "The Icelandic Loop", date: "02 Sep 2026", status: "Pending", amount: "$3,780" },
  { guest: "Aarav Mehta", route: "A Week in Rajasthan", date: "14 Oct 2026", status: "Confirmed", amount: "$2,240" },
];

export default function AdminPage() {
  return (
    <main className="min-h-screen bg-[#f5f3ee] text-[#1d2724]">
      <header className="border-b border-[#d9ded8] bg-[#fffdf9]"><div className="mx-auto flex max-w-[1180px] items-center justify-between px-6 py-6 lg:px-10"><a href="/" aria-label="GoAvir home"><img src="/images/goavir-logo.png" alt="GoAvir" className="brand-logo" /></a><div className="flex items-center gap-5 text-sm text-[#687570]"><span>Admin workspace</span><a href="/" className="font-semibold text-[#263b37]">View site ↗</a></div></div></header>
      <div className="mx-auto max-w-[1180px] px-6 py-12 lg:px-10"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#ec765e]">Overview · 04 September 2026</p><h1 className="serif mt-3 text-5xl tracking-[-.04em] text-[#263b37]">Good morning, team.</h1></div><button className="rounded-full bg-[#263b37] px-5 py-3 text-sm font-semibold text-white">+ Add new tour</button></div>
        <div className="mt-10 grid gap-4 md:grid-cols-3"><div className="bg-[#263b37] p-6 text-white"><p className="text-xs uppercase tracking-[.16em] text-[#b6c7b1]">Upcoming bookings</p><p className="serif mt-3 text-5xl">24</p><p className="mt-3 text-xs text-[#b6c7b1]">+12% from last month</p></div><div className="bg-[#e8ede5] p-6"><p className="text-xs uppercase tracking-[.16em] text-[#687570]">Live journeys</p><p className="serif mt-3 text-5xl text-[#263b37]">28</p><p className="mt-3 text-xs text-[#687570]">Across 3 trip types</p></div><div className="bg-[#f0c7a3] p-6"><p className="text-xs uppercase tracking-[.16em] text-[#687570]">This month</p><p className="serif mt-3 text-5xl text-[#263b37]">$18.4k</p><p className="mt-3 text-xs text-[#687570]">Gross booking value</p></div></div>
        <section className="mt-12 bg-[#fffdf9] p-6 md:p-8"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#ec765e]">Operations</p><h2 className="serif mt-2 text-3xl text-[#263b37]">Recent bookings</h2></div><button className="text-sm font-semibold text-[#ec765e]">View all →</button></div><div className="mt-7 overflow-x-auto"><table className="w-full min-w-[700px] border-collapse text-left text-sm"><thead><tr className="border-b border-[#d9ded8] text-[10px] uppercase tracking-[.14em] text-[#8a9690]"><th className="pb-3 font-semibold">Guest</th><th className="pb-3 font-semibold">Journey</th><th className="pb-3 font-semibold">Travel date</th><th className="pb-3 font-semibold">Status</th><th className="pb-3 text-right font-semibold">Value</th></tr></thead><tbody>{bookings.map((booking) => <tr key={booking.guest} className="border-b border-[#edf0eb]"><td className="py-5 font-semibold text-[#263b37]">{booking.guest}</td><td className="py-5 text-[#687570]">{booking.route}</td><td className="py-5 text-[#687570]">{booking.date}</td><td className="py-5"><span className={`inline-block px-3 py-1 text-[10px] font-bold uppercase tracking-[.12em] ${booking.status === "Confirmed" ? "bg-[#e8ede5] text-[#4d7056]" : "bg-[#fff0e7] text-[#bd6749]"}`}>{booking.status}</span></td><td className="py-5 text-right font-semibold text-[#263b37]">{booking.amount}</td></tr>)}</tbody></table></div></section>
      </div>
    </main>
  );
}
